name: My First Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  say-hello:
    runs-on: ubuntu-latest
    env:
      MY_NAME: Tanhab

    steps:
      - name: Checkout the code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Print secret
        run: echo "My secret is ${{ secrets.MY_SECRET_KEY }}"

      - name: Run the file
        run: node index.js